# Generated by Django 5.1.2 on 2025-11-18 11:28

import devices.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14,15}$', 'Допустимы только цифры'), devices.models.validate_imei], verbose_name='IMEI')),
                ('model_name', models.CharField(blank=True, max_length=255, verbose_name='Модель телефона')),
                ('status', models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('warranty', 'На гарантии'), ('written_off', 'Списан')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('warranty', 'На гарантии'), ('written_off', 'Списан')], max_length=20, verbose_name='Был статус')),
                ('new_status', models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('warranty', 'На гарантии'), ('written_off', 'Списан')], max_length=20, verbose_name='Новый статус')),
                ('previous_comment', models.TextField(blank=True, verbose_name='Был комментарий')),
                ('new_comment', models.TextField(blank=True, verbose_name='Новый комментарий')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'История устройства',
                'verbose_name_plural': 'История устройств',
                'ordering': ['-changed_at'],
            },
        ),
    ]
