# Generated by Django 5.1.2 on 2025-11-18 16:14

import devices.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-date_added'], 'permissions': [('can_manage_users', 'Может управлять пользователями'), ('can_restore_device', 'Может восстанавливать устройства из корзины')], 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AddField(
            model_name='device',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления в корзину'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'Допустимы только 15 цифр'), devices.models.validate_imei], verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('warranty', 'На гарантии'), ('written_off', 'Списан'), ('trash', 'В корзине')], default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='new_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('warranty', 'На гарантии'), ('written_off', 'Списан'), ('trash', 'В корзине')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='previous_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('warranty', 'На гарантии'), ('written_off', 'Списан'), ('trash', 'В корзине')], max_length=20, verbose_name='Был статус'),
        ),
    ]
