# Generated by Django 5.1.2 on 2025-11-19 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_warranty_statuses(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    DeviceHistory = apps.get_model('devices', 'DeviceHistory')
    Device.objects.filter(status='warranty').update(status='in_stock')
    DeviceHistory.objects.filter(previous_status='warranty').update(previous_status='in_stock')
    DeviceHistory.objects.filter(new_status='warranty').update(new_status='in_stock')


def seed_user_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model('devices', 'UserProfile')
    for user in User.objects.all():
        role = 'admin' if user.is_superuser else 'guest'
        UserProfile.objects.get_or_create(user=user, defaults={'role': role})


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_options_device_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_warranty_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('written_off', 'Списан'), ('trash', 'В корзине')], default='in_stock', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='new_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('written_off', 'Списан'), ('trash', 'В корзине')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='previous_status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('sold', 'Продано'), ('written_off', 'Списан'), ('trash', 'В корзине')], max_length=20, verbose_name='Был статус'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('guest', 'Гость')], default='guest', max_length=20)),
                ('can_delete_devices', models.BooleanField(default=True, help_text='Если выключено — оператор может только добавлять устройства.', verbose_name='Можно удалять устройства')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.RunPython(seed_user_profiles, migrations.RunPython.noop),
    ]
