# Generated by Django 5.1.2 on 2025-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_options_alter_device_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Полный доступ ко всем функциям, нельзя понизить.', verbose_name='Суперадминистратор'),
        ),
    ]
